{% set name = "gotrue" %}
{% set version = "2.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 250f1accf59af07941df6445d0986ce0521ffea0640a58fa64c98ad6d7d1adce

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8,<4.0
    - httpx >=0.23,<0.28
    - pydantic >=1.10,<3

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - gotrue

about:
  home: https://github.com/supabase-community/gotrue-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python client implementation of Supabase's GoTrue
  description: |
    Python client implementation of Supabase's GoTrue

extra:
  recipe-maintainers:
    - timkpaine
    - J0
    - anand2312
