{% set name = "gotrue" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9ad9b2536ca68676cf37dc663b64f259956826075e80a9cb3f5a3ba150355811

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >=3.8
    - pip
    - poetry
  run:
    - python >=3.8
    - httpx >=0.23.0
    - pydantic >=1.10.0

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - gotrue

about:
  home: https://github.com/supabase-community/gotrue-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python client implementation of Supabase's GoTrue
  description: |
    Python client implementation of Supabase's GoTrue

extra:
  recipe-maintainers:
    - timkpaine
    - J0
    - anand2312
