{% set name = "gotrue" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f80befe60d713d5b524e70591fc22df4c5be5821d370585693cd76ac8c45eeeb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - pip
    - poetry <1.6
  run:
    - python >=3.8
    - httpx >=0.23.0,<0.25
    - pydantic >=1.10.0,<3

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - gotrue

about:
  home: https://github.com/supabase-community/gotrue-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python client implementation of Supabase's GoTrue
  description: |
    Python client implementation of Supabase's GoTrue

extra:
  recipe-maintainers:
    - timkpaine
    - J0
    - anand2312
